//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub public_id: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub private: bool,
    pub archived_at: Option<DateTime>,
    pub last_activity_at: DateTime,
    pub organization_id: i64,
    pub creator_id: i64,
    pub archived_by_id: Option<i64>,
    pub slack_channel_id: Option<String>,
    pub message_thread_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub accessory: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_photo_path: Option<String>,
    pub is_general: bool,
    pub is_default: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub invite_token: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
